version: "3.3"

services:
    nginx:
        image: nginx:custom
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        ports:
            - 443:443
            - 9000
        volumes:
            - wp-data:/var/www/html
        restart: always
        networks:
            - inception
        depends_on:
            - wordpress

    wordpress:
        image: wordpress:custom
        container_name: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        ports:
            - 443:443
            - 9000
        volumes:
            - wp-data:/var/www/html
        restart: always
        networks:
            - inception
        depends_on:
            - mariadb

    mariadb:
        image: mariadb:custom
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
            args:
                - MYSQL_USER
                - MYSQL_PASSWORD
                - MYSQL_DATABASE
                - MYSQL_ROOT_PASSWORD
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        restart: always
        networks:
            - inception