version: "3.3"

services:
    nginx:
        container_name: nginx
        image: nginx:custom
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        ports:
            - 443:443
            - 9000
        volumes:
            - wpdata:/var/www/html
        restart: always
        networks:
            - inception
        depends_on:
            - wordpress

    wordpress:
        container_name: wordpress
        image: wordpress:custom
        build:
            context: ./requirements/wordpress
        env_file:
            - .env
        ports:
            - 3306
            - 9000
        volumes:
            - wpdata:/var/www/html
        restart: unless-stopped
        networks:
            - inception
        depends_on:
            - mariadb

    mariadb:
        container_name: mariadb
        image: mariadb:custom
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
            args:
                - MYSQL_USER
                - MYSQL_PASSWORD
                - MYSQL_DATABASE
                - MYSQL_ROOT_PASSWORD
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        restart: always
        networks:
            - inception

networks:
    inception:
        name: _inception
        driver: bridge

volumes:
    dbdata:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: /home/$USER/data/DB
    wpdata:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: /home/$USER/data/WordPress
